### ISSUE TITLE
Documentation improvements

### ISSUE THREAD

**Issue by klvbdmh** [jblance/powermon#9]
I setup powermon as a replacement for mpp-solar. It works pretty well so far. It took me a couple of hours to set up the config file and I already had a working instance of mpp-solar, so I wasn't working completely from scratch.

I noticed there are two sources of documentation: the repo wiki and GitHub Pages. I also used the [powermon/test/config](https://github.com/jblance/powermon/tree/master/tests/config) directory and I read the source code elsewhere in the repo. I got the hang of it more or less, but I'm still not sure about the relation between `trigger`, `keep-alive`, and `loop`. 

I'd like to help you with writing documentation for this project. For starters, I can write complete setup guides for two devices (Daly BMS and one inverter). The guides would cover picking the right cable, enabling access to the USB device for non-root, installing powermon and dependencies, and sample config files.

I don't know where to place it though: wiki or the html docs? Are you planning on keeping and maintaining both? Is there anything else you would like to improve in the docs first?

**Comment by jblance** [comment]
Hi - thanks for the offer
Yes the docs are a mess (and I keep changing where I think they should live - I also started messing with https://jblance.github.io/powermon/index.html where I started trying to document the config file)
I'd like to settle on one location and remove the others

My current thinking is the github.io makes more sense that wiki or in the repo - happy to hear your thoughts

I think capturing what you learnt during a first time setup would be a awesome start - for example I was starting to think about a 'initial config generator' script or utility

powermon is very wip and I keep changing the way it works as I run into things (so be careful about upgrades)

**Comment by klvbdmh** [comment]
> My current thinking is the github.io makes more sense that wiki or in the repo - happy to hear your thoughts

Yeah, a lot of projects have dedicated pages for documentation like github.io. Sounds good - they are generated from markdown either way. And you're right, there should be a single source of truth for the documentation.

I'll write a rough draft of my Daly BMS setup, with extra comments. Off the top of my head, Home Assistant complained when the `device: -> model:` was empty (sensors didn't update). And for some reason, my daemon only queried and sent data once on startup - until I added `loop` and `trigger`. I'll try to reproduce my original setup later.

>  I was starting to think about a 'initial config generator' script or utility

That's a great idea and I was thinking the same thing. How would it work exactly? Scan USB/Serial ports and try different protocols to see what can be detected? Or something simpler where the CLI utility guides users to select options from a list on each step?

**Comment by jblance** [comment]
> > My current thinking is the github.io makes more sense that wiki or in the repo - happy to hear your thoughts
> 
> Yeah, a lot of projects have dedicated pages for documentation like github.io. Sounds good - they are generated from markdown either way. And you're right, there should be a single source of truth for the documentation.
> 

Sounds like 2 votes for github.io - lets go with that

> I'll write a rough draft of my Daly BMS setup, with extra comments. Off the top of my head, Home Assistant complained when the `device: -> model:` was empty (sensors didn't update). And for some reason, my daemon only queried and sent data once on startup - until I added `loop` and `trigger`. I'll try to reproduce my original setup later.

loop yes, trigger shouldnt matter (rather it should default to a sensible value)

> 
> > I was starting to think about a 'initial config generator' script or utility
> 
> That's a great idea and I was thinking the same thing. How would it work exactly? Scan USB/Serial ports and try different protocols to see what can be detected? Or something simpler where the CLI utility guides users to select options from a list on each step?

I was thinking 'ask questions and generate, but havent really thought in detail'
